version: '3.8'

services:
  db:
    image: mysql
    container_name: mysql-container
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=lab6password
    ports:
      - "3306:3306"
    volumes:
      - lab6:/var/lib/mysql
volumes:
  lab6: